name: nerd_facts_pokemon
version: '1.0.0'
config-version: 2

profile: nerd_facts_pokemon

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nerd_facts_pokemon:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
